VENV = venv
PYTHON = $(VENV)/bin/python3
PIP = $(VENV)/bin/pip

$(VENV)/bin/activate: requirements.txt
	@echo "Creating virtual environment"
	python3 -m venv $(VENV)
	$(PIP) install -r requirements.txt
	touch $(VENV)/bin/activate

run: $(VENV)/bin/activate
	@echo "Activating virtual environment"
	. $(VENV)/bin/activate && $(PYTHON) app.py

streamlit: $(VENV)/bin/activate
  @echo "Activating virtual environment"
  . $(VENV)/bin/activate && streamlit run app.py


clean:
	@echo "Cleaning up"
	rm -rf __pycache__
	rm -rf $(VENV)
