VENV = venv
PYTHON = $(VENV)/bin/python
PIP = $(VENV)/bin/pip

ACTIVATE = . $(VENV)/bin/activate &&

$(VENV)/bin/activate: requirements.txt
	@echo "Creating virtual environment"
	python3 -m venv $(VENV)
	$(PIP) install -r requirements.txt
	touch $(VENV)/bin/activate

run: $(VENV)/bin/activate
	@echo "Activating virtual environment and running app.py"
	$(ACTIVATE) $(PYTHON) app.py

streamlit: $(VENV)/bin/activate
	@echo "Activating virtual environment and running Streamlit"
	$(ACTIVATE) streamlit run ui.py

clean:
	@echo "Cleaning up"
	rm -rf __pycache__
	rm -rf $(VENV)
